### ISSUE TITLE
catkin_make OAFD_Monocular

### ISSUE THREAD

**Issue by DigitalDungeon01** [geturin/OAFD_Monocular#10]
i got problem with the catkin_make and catkin build
the orb_slam3_wrapper is on catkin_build but the OAFD_Monocular package on catkin_make

when i run slam.launch in order to do slam, i got problem it says that my orb_slam3_wrapper is missing. how do i fix this?

**Comment by DigitalDungeon01** [comment]
i mean how do coorperate with catkin_make and catkin build types because for wrapper i use catkin build but the OAFD_monocular packge i need to use catkin_make. so what i do is i create a new workstation becasue i need to use catkin_make, but catkin build is on another workstation because orb_slam3_wrapper is used catkin build in order to build the package, how do fix this?

**Comment by geturin** [comment]
For issues with environment variables for multiple ROS workspaces, you can refer to the answer here. If set up correctly, it is possible to successfully include multiple workspaces without conflicts: https://github.com/geturin/OAFD_Monocular/issues/3#issuecomment-1938607606

**Comment by DigitalDungeon01** [comment]
http://wiki.ros.org/catkin/Tutorials/workspace_overlaying

fixed!, thank you so much sir for assist me. i never know about overlaying workspaces. thank you so much
