### ISSUE TITLE
problem when running slam.launch ( Gtk-ERROR **: 16:37:00.038: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported)

### ISSUE THREAD

**Issue by DigitalDungeon01** [geturin/OAFD_Monocular#11]
Loading ORB Vocabulary. This could take a while...
Traceback (most recent call last):
  File "/home/arief/FYPworkspaces/catkin_ws_OAFD/src/OAFD_Monocular/src/get_odom.py", line 5, in <module>
    import ros_numpy
  File "/opt/ros/noetic/lib/python3/dist-packages/ros_numpy/__init__.py", line 7, in <module>
    from . import point_cloud2
  File "/opt/ros/noetic/lib/python3/dist-packages/ros_numpy/point_cloud2.py", line 224, in <module>
    def get_xyz_points(cloud_array, remove_nans=True, dtype=np.float):
  File "/home/arief/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
Traceback (most recent call last):
  File "/home/arief/FYPworkspaces/catkin_ws_OAFD/src/OAFD_Monocular/src/depthmap_calibration.py", line 9, in <module>
    raise AttributeError(__former_attrs__[attr])
    from simple_tf import *
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations  File "/home/arief/FYPworkspaces/catkin_ws_OAFD/src/OAFD_Monocular/src/simple_tf.py", line 6, in <module>

    import ros_numpy
  File "/opt/ros/noetic/lib/python3/dist-packages/ros_numpy/__init__.py", line 7, in <module>
    from . import point_cloud2
  File "/opt/ros/noetic/lib/python3/dist-packages/ros_numpy/point_cloud2.py", line 224, in <module>
    def get_xyz_points(cloud_array, remove_nans=True, dtype=np.float):
  File "/home/arief/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
[pcd_pub-2] process has died [pid 10928, exit code 1, cmd /home/arief/FYPworkspaces/catkin_ws_OAFD/src/OAFD_Monocular/src/depthmap_calibration.py __name:=pcd_pub __log:=/home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/pcd_pub-2.log].
log file: /home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/pcd_pub-2*.log
[odom_pub-3] process has died [pid 10929, exit code 1, cmd /home/arief/FYPworkspaces/catkin_ws_OAFD/src/OAFD_Monocular/src/get_odom.py __name:=odom_pub __log:=/home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/odom_pub-3.log].
log file: /home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/odom_pub-3*.log
Vocabulary loaded!

Creation of new map with id: 0
Creation of new map with last KF id: 0
Seq. Name: 

Camera Parameters: 
- Camera: Pinhole
- fx: 910.072
- fy: 914.094
- cx: 485.523
- cy: 336.718
- k1: -0.005941
- k2: 0.055161
- p1: -0.006094
- p2: 0.003192
- fps: 20
- color order: BGR (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7
Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.
(ORB-SLAM3: Current Frame:10927): Gtk-ERROR **: 16:37:00.038: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
[orb_slam3_mono-1] process has died [pid 10927, exit code -5, cmd /home/arief/FYPworkspaces/tello_ros1_ws/devel/lib/orb_slam3_ros_wrapper/orb_slam3_ros_wrapper_mono __name:=orb_slam3_mono __log:=/home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/orb_slam3_mono-1.log].
log file: /home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/orb_slam3_mono-1*.log
[ WARN] [1716626229.934427833]: No transform between frames /map and /camera available after 20.118962 seconds of waiting. This warning only prints once.

**Comment by DigitalDungeon01** [comment]
Loading ORB Vocabulary. This could take a while...
Vocabulary loading failure: This is not a correct text file!
Wrong path to vocabulary. 
Falied to open at: /home/arief/FYPworkspaces/tello_ros1_ws/src/orb_slam3_ros_wrapper/config/ORBvoc.txt
Traceback (most recent call last):
  File "/home/arief/FYPworkspaces/catkin_ws_OAFD/src/OAFD_Monocular/src/get_odom.py", line 5, in <module>
    import ros_numpy
  File "/opt/ros/noetic/lib/python3/dist-packages/ros_numpy/__init__.py", line 7, in <module>
    from . import point_cloud2
  File "/opt/ros/noetic/lib/python3/dist-packages/ros_numpy/point_cloud2.py", line 224, in <module>
    def get_xyz_points(cloud_array, remove_nans=True, dtype=np.float):
  File "/home/arief/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Traceback (most recent call last):
  File "/home/arief/FYPworkspaces/catkin_ws_OAFD/src/OAFD_Monocular/src/depthmap_calibration.py", line 9, in <module>
    from simple_tf import *
  File "/home/arief/FYPworkspaces/catkin_ws_OAFD/src/OAFD_Monocular/src/simple_tf.py", line 6, in <module>
    import ros_numpy
  File "/opt/ros/noetic/lib/python3/dist-packages/ros_numpy/__init__.py", line 7, in <module>
    from . import point_cloud2
  File "/opt/ros/noetic/lib/python3/dist-packages/ros_numpy/point_cloud2.py", line 224, in <module>
    def get_xyz_points(cloud_array, remove_nans=True, dtype=np.float):
  File "/home/arief/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
[orb_slam3_mono-1] process has died [pid 9750, exit code 255, cmd /home/arief/FYPworkspaces/tello_ros1_ws/devel/lib/orb_slam3_ros_wrapper/orb_slam3_ros_wrapper_mono __name:=orb_slam3_mono __log:=/home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/orb_slam3_mono-1.log].
log file: /home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/orb_slam3_mono-1*.log
[pcd_pub-2] process has died [pid 9751, exit code 1, cmd /home/arief/FYPworkspaces/catkin_ws_OAFD/src/OAFD_Monocular/src/depthmap_calibration.py __name:=pcd_pub __log:=/home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/pcd_pub-2.log].
log file: /home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/pcd_pub-2*.log
[odom_pub-3] process has died [pid 9752, exit code 1, cmd /home/arief/FYPworkspaces/catkin_ws_OAFD/src/OAFD_Monocular/src/get_odom.py __name:=odom_pub __log:=/home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/odom_pub-3.log].
log file: /home/arief/.ros/log/46d8b71c-1a6b-11ef-9e37-8949fe58c0f8/odom_pub-3*.log

**Comment by DigitalDungeon01** [comment]
i fix it by insert the orbtext voc text into right place then need to do some modifcation on the launch file

**Comment by geturin** [comment]
For the numpy issue, my environment had numpy version 1.17.4 at that time. You can try rolling back to this version or modify the code to change the deprecated np.datatype. For the GTK issue, you can refer to this: 

https://github.com/thien94/orb_slam3_ros_wrapper/issues/19
https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/286

 It looks like you need to recompile OpenCV

**Comment by DigitalDungeon01** [comment]
https://github.com/Mauhing/ORB_SLAM3/blob/master/README.md i follow this in order to build openCV package but use opencv 4.4.0 

just follow this instructions : https://github.com/thien94/orb_slam3_ros_wrapper/issues/16#issuecomment-1234179588 

for the numpy, i downgrade the version to version 1.17.4

then all good!
thank you sir for your help !
