### ISSUE TITLE
Use DSO instead of ORB-SLAM3

### ISSUE THREAD

**Issue by RavDas** [geturin/OAFD_Monocular#5]
What changes in the code are required if I try it on DSO instead of ORB-SLAM3?

**Comment by geturin** [comment]
I have retrieved the camera's pose stamped and the point cloud of key points tracked in each frame from ORB_SLAM3 for calculations. may be you can publish these data from DSO to ROS.

https://github.com/geturin/OAFD_Monocular/blob/41f98f3fb53c3250187efc55c2893373dc32cfbc/src/get_odom.py#L45C1-L45C63

https://github.com/geturin/OAFD_Monocular/blob/41f98f3fb53c3250187efc55c2893373dc32cfbc/src/depthmap_calibration.py#L113
