### ISSUE TITLE
fatal error: sophus/se3.hpp: No such file or directory

### ISSUE THREAD

**Issue by DigitalDungeon01** [geturin/OAFD_Monocular#9]
ude/FrameDrawer.h:24,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/Viewer.h:23,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/Tracking.h:26,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/System.h:31,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/orb_slam3_ros_wrapper/include/common.h:27,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/orb_slam3_ros_wrapper/src/mono_node.cc:7:
/home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/ImuTypes.h:29:10: fatal error: sophus/se3.hpp: No such file or directory
   29 | #include <sophus/se3.hpp>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/orb_slam3_ros_wrapper_mono.dir/build.make:63: CMakeFiles/orb_slam3_ros_wrapper_mono.dir/src/mono_node.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/Frame.h:30,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/KeyFrame.h:28,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/MapPoint.h:23,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/FrameDrawer.h:24,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/Viewer.h:23,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/Tracking.h:26,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/System.h:31,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/orb_slam3_ros_wrapper/include/common.h:27,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/orb_slam3_ros_wrapper/src/common.cc:7:
/home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/ImuTypes.h:29:10: fatal error: sophus/se3.hpp: No such file or directory
   29 | #include <sophus/se3.hpp>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/orb_slam3_ros_wrapper_mono_inertial.dir/build.make:76: CMakeFiles/orb_slam3_ros_wrapper_mono_inertial.dir/src/common.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1543: CMakeFiles/orb_slam3_ros_wrapper_mono_inertial.dir/all] Error 2
In file included from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/Frame.h:30,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/KeyFrame.h:28,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/MapPoint.h:23,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/FrameDrawer.h:24,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/Viewer.h:23,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/Tracking.h:26,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/System.h:31,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/orb_slam3_ros_wrapper/include/common.h:27,
                 from /home/arief/FYPworkspaces/tello_ros1_ws/src/orb_slam3_ros_wrapper/src/common.cc:7:
/home/arief/FYPworkspaces/tello_ros1_ws/src/ORB_SLAM3/include/ImuTypes.h:29:10: fatal error: sophus/se3.hpp: No such file or directory
   29 | #include <sophus/se3.hpp>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/orb_slam3_ros_wrapper_mono.dir/build.make:76: CMakeFiles/orb_slam3_ros_wrapper_mono.dir/src/common.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:814: CMakeFiles/orb_slam3_ros_wrapper_mono.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/arief/FYPworkspaces/tello_ros1_ws/build/orb_slam3_ros_wrapper; catkin build --get-env orb_slam3_ros_wrapper | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

got an error when trying to build orb slam3 wrapper

**Comment by geturin** [comment]
The error message indicates that the dependency sophus for IMUTypes.h in ORB_SLAM3 cannot be found. 

 However, the version of ORB_SLAM3 used in my project should not include this dependency. Please make sure to roll back the ORB_SLAM3 version as instructed in the README and compile it, and also compile using the older version of orb_slam3_ros_wrapper that I forked.

**Comment by DigitalDungeon01** [comment]
all fixed thank you so much
